// <auto-generated />
namespace GS_Shop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Intinial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intinial));
        
        string IMigrationMetadata.Id
        {
            get { return "201905140952007_Intinial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
